### PR TITLE
Add support for FullScreen API

### PR DESCRIPTION
**Pull request by garth**
See #414 and #415

### CODE REVIEW

**Comment by garth** [comment]
Until support for the FullScreen API is merged/added in to the official lib, a modified version of `react-sortable-hoc` with only this PR added has been published to npm.

```
yarn add react-sortable-hoc-fullscreen
```

**Comment by clauderic** [comment]
I believe you could use the newly added `helperContainer` prop instead to achieve the same functionality. Going to close this for now unless there is a strong case to be made to support this natively

**Comment by garth** [comment]
@clauderic no, doesn't work. To fix, helperContainer would have a to accept a function that is evaluated when the drag begins.

**Comment by garth** [comment]
In case someone finds this issue, since version 1.5.2 you can do the following to get fullscreen support:

```tsx
<SortableList
  helperContainer={() =>
    document['fullscreenElement'] ||
    document['webkitFullscreenElement'] ||
    document['mozFullScreenElement'] ||
    document['msFullscreenElement'] ||
    document.body
  }
/>
```

**Comment by clauderic** [comment]
Thanks for sharing back your solution @garth

**Pull request closed without merging**
