### PR TITLE
when creating the ghost element for drag effect, copy the canvas content as well

### PR DESCRIPTION
**Pull request by ssinghi**
Fixes issues #330.

### CODE REVIEW

**Comment by tzachyrm** [comment]
+1

@clauderic any idea if and when this is going to be merged?

**Comment by tzachyrm** [comment]
@pritam1994 thanks for approving this. who is responsible for merging?

**Comment by tzachyrm** [comment]
@clauderic can you please merge this?

**Comment by Benjaki2** [comment]
+1

**Comment by tzachyrm** [comment]
@clauderic any chance of merging this soon?

**Comment by clauderic** [comment]
Integrated this fix in this commit https://github.com/clauderic/react-sortable-hoc/commit/43ad122bbed56b9ece79e48ff2d08d30a6503554, which shipped with `react-sortable-hoc@1.8.0`

**Pull request closed without merging**
