### PR TITLE
Add RTL support (based on #462)

### LINKED ISSUE #370: Problem with rtl direction
When I use rtl direction for container sort is not working correctly

demo: https://jsfiddle.net/eckfano0/2/

```css
.item {
  cursor: move;
  padding: 8px;
  border: 1px solid red;
}

.container {
  display: flex;
  flex-direction: row;
  direction: rtl;
}
```
Is there any way to support rtl directino?

### PR DESCRIPTION
**Pull request by felixmosh**
First of all, all the thanks goes to @PersianArt, thanks for the original PR.

I've just made a new and fresh PR from master + examples.

Fixes #370 issue

### CODE REVIEW

**Comment by felixmosh** [comment]
Fixes #370 issue

**Comment by felixmosh** [comment]
@clauderic can you review this PR pls?

**Comment by felixmosh** [comment]
@clauderic, Ping

**Comment by felixmosh** [comment]
@clauderic ping 2

**Comment by felixmosh** [comment]
?

**Comment by david1824** [comment]
Hey, any updates here?

**Comment by Kavian77** [comment]
Hey, any updates?

**Comment by roeycohen** [comment]
hi @felixmosh, 10q for replying to me in #462 :)
It doesn't seem like anyone is processing pull requests...
Is code published somewhere else?

**Pull request closed without merging**
