### PR TITLE
Use new react context!

### PR DESCRIPTION
**Pull request by lindskogen**
Continued the work of @natew 

Also I moved the createContext call underneath all the import statements because my vscode was complaining about that.

### CODE REVIEW

**Comment by natew** [comment]
Nice, thanks for taking this. I just don’t have bandwidth for it. Would love to see this library concurrent compatible, it’s the only thing holding us up at the moment!

**Comment by Hypnosphi** [comment]
@clauderic Can you please review this? React Concurrent mode is getting closer every day =)

**Comment by devmrin** [comment]
Hi, any update on this PR?

**Comment by jancama2** [comment]
@clauderic Hi, how does it look like with the review? :)

**Comment by o-gent** [comment]
@clauderic Hi, what's the issue with getting this merged?

**Comment by mrleemon** [comment]
Can anyone merge this, please? My console is full of "Legacy context API has been detected within a strict-mode tree" warnings.

**Comment by davvilla** [comment]
Hello, I'm getting a ton of the legacy API warnings. Are there any plans to merge this to fix them?

Thanks!

**Comment by hamzamubeen-rebel** [comment]
Hi when will this PR be merged or will it be ..?

**Pull request merged**
