### PR TITLE
Delete setting the value for file inputs

### PR DESCRIPTION
**Pull request by strikepark**
Add a file to the input item and drag it, then open DevTools, you will see this error:
`Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.`
Example: https://jsfiddle.net/60848oue/1/

### CODE REVIEW

**Comment by clauderic** [comment]
Hey @strikepark would you mind rebasing or giving me write access to your PR?

**Comment by strikepark** [comment]
I'm sorry but I deleted my forked repo a long time ago.

**Comment by flash-gordon** [comment]
@clauderic check out https://github.com/clauderic/react-sortable-hoc/pull/232

**Comment by clauderic** [comment]
Closing in favor of #232

**Pull request closed without merging**
