### PR TITLE
Add support for CSS grids

### PR DESCRIPTION
**Pull request by andrewcoelho**
Hey, first off thanks for the great project!

This PR addresses a small bug I ran into using the HOC's grid functionality with CSS grid styles.

Currently, items in a CSS grid are not translated correctly while sorting. This is because the translate offset is only using an item's `margin` to determine its translation amount. In a CSS grid, the `grid-gap`, `grid-column-gap`, and `grid-row-gap` properties can be used on a container to add spacing between its child elements. 

Also whipped up a repro of the issue, try dragging items around and you'll see the items being placed incorrectly during sorting and then shift to the correct positions on sort end.

https://codesandbox.io/s/vm917ww2z3

### CODE REVIEW

**Comment by iam-medvedev** [comment]
@andrewcoelho can you update this? thanks

**Comment by andrewcoelho** [comment]
@iam-medvedev updated, would be nice to get this one merged in...

**Comment by iam-medvedev** [comment]
@clauderic

**Comment by akash247** [comment]
Hi @clauderic, when can we expect this to be merged?

**Comment by mmazzarolo** [comment]
Hi! Any news? I tried it and it seem to be working fine

**Comment by RyanCCollins** [comment]
Does this allow for variable sized items?

**Comment by clauderic** [comment]
Closed in favour of #657

**Pull request closed without merging**
