### PR TITLE
Add support for yx and xy grid sorting

### PR DESCRIPTION
**Pull request by jalembke**
feature addition for a fix to issue #246 add yx to the grid sorting options.

### CODE REVIEW

**Comment by jlwatkins** [comment]
Yes! Big fan. @jalembke

**Comment by jalembke** [comment]
@clauderic Curious if anyone has had a chance to take a look at this request.  Looking to integrate this into my project using the official repository.

**Comment by iKBAHT** [comment]
@jalembke  it doesn't work for my situation. I have container with
```
flex-direction: column;
flex-wrap: wrap;
```
See pic.

**Comment by iKBAHT** [comment]
Rebase your PR to latest master
https://github.com/iKBAHT/react-sortable-hoc

**Comment by warrenmcquinn** [comment]
Hey there @jalembke - thanks for adding this PR! Any chance we can get it rebased and merged?

**Comment by puneetgupta047** [comment]
Looking for this change in official repository to add this into my project. When can this be released?

**Pull request closed without merging**
