### PR TITLE
feat: animate helper back into place on drop

### LINKED ISSUE #217: Animate into place
I'd be curious if there's interest in having the item animate into place once sorted. I'm not actually sure the best way to do this, because currently `onSortEnd` it rerenders the list.

Thanks!
Nick

### PR DESCRIPTION
**Pull request by clauderic**
Resolves #217

This PR adds support for animating the sortable helper into place on drop. It introduces two new props, `dropAnimationDuration` and `dropAnimationEasing`. Setting the `dropAnimationDuration` prop to `0` disables the transition.

Kapture 2019-03-20 at 22 46 16

Kapture 2019-03-20 at 22 42 57

### To-do:

- [x] Fix issues with virtualization libraries
- [x] Add story for disabling drop animation

### CODE REVIEW

**Comment by gantit** [comment]
This request resolve this issue? https://github.com/clauderic/react-sortable-hoc/issues/520

**Comment by clauderic** [comment]
> This request resolve this issue? #520

No, that sounds like a separate issue

**Comment by selva-ts** [comment]
Hi, when this animation PR will be merged into master?

**Comment by Motoxpro** [comment]
I'd like to see this one aswell!

**Comment by mguidetti** [comment]
Would really love to see this merged as well. 🙏🏻

**Comment by mguidetti** [comment]
Would really love to see this merged as well. 🙏🏻

**Comment by ktonini** [comment]
@clauderic Any chance this will be merged soon? Looking forward to using this feature!

**Comment by VijiGeo** [comment]
@clauderic Looking forward to this feature as well!

**Comment by yuuk** [comment]
need this feature！

**Comment by clauderic** [comment]
Closing this PR as I no longer have plans to add this functionality to `react-sortable-hoc` for the time being. Consider migrating to [`@dnd-kit`](https://github.com/clauderic/dnd-kit) which supports drop animations out of the box if you want this feature.

**Pull request closed without merging**
