### PR TITLE
Fix for using window as scrolling container

### PR DESCRIPTION
**Pull request by aminland**
Right now, even in the story book, this is broken on chrome, ff, & edge.

This just fixes it to not use document.body to set the scroll. There was also an issue with double computation in the  animateNodes function, where if the scrollcontainer was set to the parent, and we calculate both window and parent separately, it's a problem. So the key is to just use the scrollcontainer to SET the scroll value, and assume both window and container can scroll.

### CODE REVIEW

**Comment by aminland** [comment]
Any updates on this? I would love to stop using some weird fork installing from github in my packages.json

**Comment by ambewas** [comment]
@clauderic there are a number of issues open for this. Is it possible to review this PR and release a fixed version?

**Comment by yuval-vibo** [comment]
Hi,
Any updates on this issue? waiting for a fix anxiously

**Comment by ambewas** [comment]
@yuval-vibo this has taken such a long time, I've forked the repo and published the dist folder myself.
Feel free to use this version where it has been fixed: https://github.com/ambewas/react-sortable-hoc

you can install it on npm like this:
`npm install git+https://github.com/ambewas/react-sortable-hoc.git`

@clauderic  I'm sure a lot of people would like to see this fixed in the main package...

**Comment by yuval-vibo** [comment]
@ambewas Thanks Man!

**Comment by aminland** [comment]
Until this repo starts accepting pull requests, you can get our company's [version](/aminland/react-sortable-hoc/) from [npm](https://www.npmjs.com/package/@fellow/react-sortable-hoc) directly: `npm install --save @fellow/react-sortable-hoc`

**Comment by fabioimpe** [comment]
@aminland With your changes there's a strange behaviour in iOS:
temp

**Comment by aminland** [comment]
@fabioimpe This should be fixed now.

**Comment by brybrophy** [comment]
@clauderic Any progress on getting this merged in? Considering forking and merging because a client is requesting a fix immediately, but I will hold if if you plan on merging this soon.

**Comment by rafael-sap** [comment]
I also need this fix!

**Comment by aminland** [comment]
I am maintaining the npm repo @fellow/react-sortable-hoc in light of this
one not being maintained...

**Comment by mattes3** [comment]
Will this be merged in? I need it urgently because a client of mine is complaining, too!

I cannot use @fellow/react-sortable-hoc because the Typescript compiler won't import it because it cannot find @types/@fellow/react-sortable-hoc

So, I'm interested to get an official solution that also works with Typescript.

**Comment by EricFries** [comment]
Cool library--it would be great to see this fix get merged in.

**Comment by eveningkid** [comment]
This PR fixes it all. @clauderic, please, it would help everyone to have this working...
@aminland's work saved my day. Thanks :)

**Pull request merged**
