### PR TITLE
Auto scrolling is improved

### PR DESCRIPTION
**Pull request by praya**
this merge resolves this issue:
#242

### CODE REVIEW

**Comment by praya** [comment]
@clauderic what do you think about this changes?

**Comment by praya** [comment]
Is anybody here?

**Comment by clauderic** [comment]
Released in 1.54, thanks!

**Comment by praya** [comment]
Thank you!)

**Comment by pedrommarquesm** [comment]
This somehow got lost in earlier versions. wasn't this mistakenly not frontported to new versions?
The original issue is still reproducible

**Pull request merged**
